### ISSUE TITLE
mrbdoc header file error

### ISSUE THREAD

**Issue by ghost** [sagmor/yard-mruby#14]
I'm currently developing my own mrbgem and for some reason I keep getting this error when I add ``include/*.h`` in the ``.yardopts`` it gives me this error:

``file_system_serializer.rb:88:in `block in build_filename_map': undefined method `+' for :"mrb_bb_rpg.h":Symbol (NoMethodError)``

My ``.yardopt`` file looks like this when the error happens:
```
--markup markdown
--plugin mruby
--plugin coderay
--output-dir doc/api

src/*.c
include/*.h
mrblib/*.rb
test/*.rb
```

**Comment by sagmor** [comment]
Closed by #15 & #16 Thanks to @jmhmccr
